POST /competition/awdController/submitFlag HTTP/1.1
Host: 10.100.1.12:2301
Accept-Language: zh-CN
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0
Accept: application/json, text/plain, */*
Origin: http://10.100.1.12:2301
Referer: http://10.100.1.12:2301/
X-Requested-With: XMLHttpRequest
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTIwNDIwNjgsInVzZXJJZCI6IjViMTE3NmI3YWI5N2ZkOWMwYTVlYzZmNzI5ODBhN2FkIn0.d9SAWEdr0odBd_59fl45IElnkK4qABgoaqTAn3g1EQ8
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 129

competitionId=e3b598963b631d503b55fc2f41e9e97e&commitFlag=$FLAG&commitDockerIp=$IP